// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGgY4oqDvib8egJ8AXU5WIHEUlfzU49zQ',
    appId: '1:1056630945037:web:188a97c12c63392971ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    authDomain: 'tbcareappmain.firebaseapp.com',
    storageBucket: 'tbcareappmain.firebasestorage.app',
    measurementId: 'G-LXVPB3WZFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IUeeC0wKXSq2onXlgi2UwF_XLf4a7Bk',
    appId: '1:1056630945037:android:aa07b557781040f971ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    storageBucket: 'tbcareappmain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rCwk7lApcEzPyqGbWynEygCtZ09C4TQ',
    appId: '1:1056630945037:ios:86a1c009d9225ace71ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    storageBucket: 'tbcareappmain.firebasestorage.app',
    androidClientId: '1056630945037-24d8jrdjo6sorrc427p9ifrv6imhibef.apps.googleusercontent.com',
    iosClientId: '1056630945037-a75psottql5o8o2d2hg5u788egqp7aoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbcareMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rCwk7lApcEzPyqGbWynEygCtZ09C4TQ',
    appId: '1:1056630945037:ios:86a1c009d9225ace71ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    storageBucket: 'tbcareappmain.firebasestorage.app',
    androidClientId: '1056630945037-24d8jrdjo6sorrc427p9ifrv6imhibef.apps.googleusercontent.com',
    iosClientId: '1056630945037-a75psottql5o8o2d2hg5u788egqp7aoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbcareMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGgY4oqDvib8egJ8AXU5WIHEUlfzU49zQ',
    appId: '1:1056630945037:web:ae7bfaeebffcf8c271ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    authDomain: 'tbcareappmain.firebaseapp.com',
    storageBucket: 'tbcareappmain.firebasestorage.app',
    measurementId: 'G-MD9VCJL64W',
  );

}